#!/usr/bin/env bash
# The password for the next level is stored in the file data.txt, which is a hexdump of a file that has been repeatedly compressed. For this level it may be useful to create a directory under /tmp in which you can work. Use mkdir with a hard to guess directory name. Or better, use the command “mktemp -d”. Then copy the datafile using cp, and rename it using mv (read the manpages!)

# Basically just unzip using gunzip, bunzip2 and tar.
# FO5dwFsc0cbaIiH0h8J2eUks2vdTDwAn
