#!/usr/bin/env bash
# The password for the next level is stored somewhere on the server and has all of the following properties:
# owned by user bandit7
# owned by group bandit6
# 33 bytes in size

# find / -size 33c -user bandit7 -group bandit6 
# morbNTDkSW6jIlUc0ymOdMaLnOlFVAaj
