#!/usr/bin/env bash
# The password for the next level is stored in a file somewhere under the inhere directory and has all of the following properties:
# human-readable
# 1033 bytes in size
# not executable

# find . -type f -size 1033c ! -executable -exec file {} \; | grep "ASCII text"
# HWasnPhtq9AVKe0dmk45nxy20cvUa6EG 
